GH Actions: Separate Linux build to use containers.

diff --git a/.github/workflows/ci-conda-deployment.yml b/.github/workflows/ci-conda-deployment.yml
--- a/.github/workflows/ci-conda-deployment.yml
+++ b/.github/workflows/ci-conda-deployment.yml
@@ -29,43 +29,62 @@ defaults:
     shell: bash
 
 jobs:
-  build:
-    name: ${{ matrix.name }}
-    runs-on: ${{ matrix.os }}
+   build-linux:
+    name: Linux Python ${{ matrix.python-version }}
+    runs-on: ubuntu-latest
     container: ${{ matrix.container }}
     strategy:
       matrix:
-        include:
-          - name: Linux Python 3.8
-            os: ubuntu-latest
-            container: centos:centos7
-            python-version: "3.8"
-            conda-os: "Linux-x86_64" 
-          - name: Linux Python 3.9
-            os: ubuntu-latest
-            container: centos:centos7
-            python-version: "3.9"
-            conda-os: "Linux-x86_64"
-          - name: Linux Python 3.10
-            os: ubuntu-latest
-            container: centos:centos7
-            python-version: "3.10"
-            conda-os: "Linux-x86_64"
-          - name: MacOS Python 3.8
-            os: macos-10.15
-            container: none
-            python-version: "3.8"
-            conda-os: "MacOSX-x86_64"
-          - name: MacOS Python 3.9
-            os: macos-10.15
-            container: none
-            python-version: "3.9"
-            conda-os: "MacOSX-x86_64"
-          - name: MacOS Python 3.10
-            os: macos-10.15
-            container: none
-            python-version: "3.10"
-            conda-os: "MacOSX-x86_64"
+        container: centos:centos7
+        conda-os: "Linux-x86_64"
+        python-version: ["3.8", "3.9", "3.10"]
+          
+    steps:
+    - name: Checkout Code
+      uses: actions/checkout@v2
+      with:
+        submodules: 'True'
+
+    - name: Conda Setup
+      env:
+        CONDA_OS: ${{ matrix.conda-os }}
+      run: |
+        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-${CONDA_OS}.sh -O miniconda.sh
+        bash miniconda.sh -b -p ${miniconda_loc}
+        source ${miniconda_loc}/etc/profile.d/conda.sh
+        conda create -yq -n builder conda-build conda-verify
+
+    - name: Install git
+      run: yum install -y -q git
+
+    - name: Build Sherpa
+      env:
+        SHERPA_PYTHON_VERSION: ${{ matrix.python-version }}
+      run: |
+        export SHERPA_FULL_VERSION=$(git describe --tags --always)
+        export SHERPA_VERSION=$(echo $SHERPA_FULL_VERSION | awk '{split($0,a,"-"); print a[1]}')
+        export SHERPA_BUILD_NUMBER=$(echo $SHERPA_FULL_VERSION | awk '{split($0,a,"-"); print a[2]}')
+        echo "Version: ${SHERPA_VERSION} Build Number: ${SHERPA_BUILD_NUMBER}"
+        source ${miniconda_loc}/etc/profile.d/conda.sh
+        conda activate builder
+        echo "conda build --python ${SHERPA_PYTHON_VERSION} --output-folder ${GITHUB_WORKSPACE}/packages recipes/conda"
+        conda build --python ${SHERPA_PYTHON_VERSION} --output-folder ../packages recipes/conda
+
+    - uses: actions/upload-artifact@v3
+      with:
+        path: ../packages
+        if-no-files-found: error
+        retention-days: 3
+
+ 
+  build-macos:
+    name: MacOS Python ${{ matrix.python-version }}
+    runs-on: ${{ matrix.os-type }}
+    strategy:
+      matrix:
+        os-type: macos-10.15
+        conda-os: "MacOSX-x86_64"
+        python-version: ["3.8", "3.9", "3.10"]
 
     steps:
     - name: Checkout Code
@@ -83,7 +102,7 @@ jobs:
         conda create -yq -n builder conda-build conda-verify
 
     - name: macOS 10.9 SDK
-      if: ${{ matrix.conda-os == 'MacOSX' }}
+      if: ${{ matrix.conda-os == 'MacOSX-x86_64' }}
       run: |
         #Download the MacOS 10.9 SDK to the CONDA_BUILD_SYSROOT location for the Conda Compilers to work
         mkdir -p ${GITHUB_WORKSPACE}/10.9SDK
@@ -113,46 +132,36 @@ jobs:
         retention-days: 3
 
   pre-deploy-test:
-    needs: build
+    needs: [build-linux, build-macos]
     name: ${{ matrix.name }}
     runs-on: ${{ matrix.os }}
-    container: ${{ matrix.container }}
     strategy:
       matrix:
         include:
           - name: Latest Ubuntu Pre-Deploy Test
             os: ubuntu-latest
-            container: none
-            conda-os: "Linux-x86_64"
-          - name: Fedora 36 Pre-Deploy Test
-            os: ubuntu-latest
-            container: fedora:36
             conda-os: "Linux-x86_64"
           - name: Latest MacOS Pre-Deploy Test
             os: macos-latest
-            container: none
             conda-os: "MacOSX-x86_64"
 
     steps:
-    - name: Conda Setup
+    #Download all artifacts
+    - uses: actions/download-artifact@v3
+
+    - name: Conda Setup & Index Artifacts
       env:
         CONDA_OS: ${{ matrix.conda-os }}
       run: |
         wget https://repo.anaconda.com/miniconda/Miniconda3-latest-${CONDA_OS}.sh -O miniconda.sh
         bash miniconda.sh -b -p ${miniconda_loc}
         source ${miniconda_loc}/etc/profile.d/conda.sh
-
-    #Download all artifacts
-    - uses: actions/download-artifact@v3
-
-    - name: Index the downloads
-      run: |
-        source ${miniconda_loc}/etc/profile.d/conda.sh
         conda install conda-build
         conda index packages
 
     - name: Run the tests
       run: |
+        source ${miniconda_loc}/etc/profile.d/conda.sh
         curl -LO -k https://github.com/sherpa/sherpa-test-data/archive/main.zip 
         conda create -n test38 --yes -q -c file://$(pwd)/packages python=3.8 astropy sherpa matplotlib
         conda activate test38
@@ -196,6 +205,10 @@ jobs:
       run: |
         source ${miniconda_loc}/etc/profile.d/conda.sh
         conda activate
+        if [ -z ${CONDA_UPLOAD_TOKEN} ] || [ -z ${sherpa_channel} ]; then
+          echo "Error: CONDA_UPLOAD_TOKEN or sherpa_channel is not set."
+          exit 1
+        fi
         #We can switch this to use "--force" if we run into issues with the upload cutting or needing to re-run
         anaconda -t ${CONDA_UPLOAD_TOKEN} upload -u ${sherpa_channel} -l ${sherpa_label} packages/linux-64/sherpa*
         anaconda -t ${CONDA_UPLOAD_TOKEN} upload -u ${sherpa_channel} -l ${sherpa_label} packages/osx-64/sherpa*
