GH Actions: Comment out the macOS builds/tests temporarily

diff --git a/.github/workflows/ci-conda-deployment.yml b/.github/workflows/ci-conda-deployment.yml
--- a/.github/workflows/ci-conda-deployment.yml
+++ b/.github/workflows/ci-conda-deployment.yml
@@ -88,68 +88,68 @@ jobs:
         if-no-files-found: error
         retention-days: 3
 
-  build-macos:
-    name: MacOS Python ${{ matrix.python-version }}
-    runs-on: ${{ matrix.os-type }}
-    strategy:
-      matrix:
-        os-type: ["macos-10.15"]
-        conda-os: ["MacOSX-x86_64"]
-        python-version: ["3.8", "3.9", "3.10"]
-
-    steps:
-    - name: Conda Setup
-      env:
-        CONDA_OS: ${{ matrix.conda-os }}
-      run: |
-        curl -L https://repo.anaconda.com/miniconda/Miniconda3-latest-${CONDA_OS}.sh -o miniconda.sh
-        bash miniconda.sh -b -p ${miniconda_loc}
-        source ${miniconda_loc}/etc/profile.d/conda.sh
-        conda create -yq -n builder conda-build conda-verify
-
-    - name: macOS 10.9 SDK
-      if: ${{ matrix.conda-os == 'MacOSX-x86_64' }}
-      run: |
-        #Download the MacOS 10.9 SDK to the CONDA_BUILD_SYSROOT location for the Conda Compilers to work
-        mkdir -p /opt
-        curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz -o MacOSX10.9.sdk.tar.xz
-        if [[ $? -ne 0 ]]; then
-            echo "MacOS 10.9 SDK download failed"
-        fi
-        sudo tar -C /opt -xf MacOSX10.9.sdk.tar.xz
-
-    - name: Checkout Code
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
-        path: sherpa
-
-    - name: Build Sherpa
-      env:
-        SHERPA_PYTHON_VERSION: ${{ matrix.python-version }}
-      run: |
-        cd sherpa
-        export SHERPA_FULL_VERSION=$(git describe --tags --always)
-        export SHERPA_VERSION=$(echo $SHERPA_FULL_VERSION | awk '{split($0,a,"-"); print a[1]}')
-        export SHERPA_BUILD_NUMBER=$(echo $SHERPA_FULL_VERSION | awk '{split($0,a,"-"); print a[2]}')
-        echo "Version: ${SHERPA_VERSION} Build Number: ${SHERPA_BUILD_NUMBER}"
-        if [ -z ${SHERPA_VERSION} ] || [ -z ${SHERPA_BUILD_NUMBER} ] ; then
-          echo "Error: SHERPA_VERSION or SHERPA_BUILD_NUMBER not set"
-          exit 1
-        fi
-        source ${miniconda_loc}/etc/profile.d/conda.sh
-        conda activate builder
-        echo "conda build --python ${SHERPA_PYTHON_VERSION} --output-folder ${GITHUB_WORKSPACE}/packages recipes/conda"
-        conda build --python ${SHERPA_PYTHON_VERSION} --output-folder ${GITHUB_WORKSPACE}/packages recipes/conda
-
-    - uses: actions/upload-artifact@v3
-      with:
-        path: ${{ github.workspace }}/packages/*/sherpa*bz2
-        if-no-files-found: error
-        retention-days: 3
+#  build-macos:
+#    name: MacOS Python ${{ matrix.python-version }}
+#    runs-on: ${{ matrix.os-type }}
+#    strategy:
+#      matrix:
+#        os-type: ["macos-10.15"]
+#        conda-os: ["MacOSX-x86_64"]
+#        python-version: ["3.8", "3.9", "3.10"]
+#
+#    steps:
+#    - name: Conda Setup
+#      env:
+#        CONDA_OS: ${{ matrix.conda-os }}
+#      run: |
+#        curl -L https://repo.anaconda.com/miniconda/Miniconda3-latest-${CONDA_OS}.sh -o miniconda.sh
+#        bash miniconda.sh -b -p ${miniconda_loc}
+#        source ${miniconda_loc}/etc/profile.d/conda.sh
+#        conda create -yq -n builder conda-build conda-verify
+#
+#    - name: macOS 10.9 SDK
+#      if: ${{ matrix.conda-os == 'MacOSX-x86_64' }}
+#      run: |
+#        #Download the MacOS 10.9 SDK to the CONDA_BUILD_SYSROOT location for the Conda Compilers to work
+#        mkdir -p /opt
+#        curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz -o MacOSX10.9.sdk.tar.xz
+#        if [[ $? -ne 0 ]]; then
+#            echo "MacOS 10.9 SDK download failed"
+#        fi
+#        sudo tar -C /opt -xf MacOSX10.9.sdk.tar.xz
+#
+#    - name: Checkout Code
+#      uses: actions/checkout@v2
+#      with:
+#        fetch-depth: 0
+#        path: sherpa
+#
+#    - name: Build Sherpa
+#      env:
+#        SHERPA_PYTHON_VERSION: ${{ matrix.python-version }}
+#      run: |
+#        cd sherpa
+#        export SHERPA_FULL_VERSION=$(git describe --tags --always)
+#        export SHERPA_VERSION=$(echo $SHERPA_FULL_VERSION | awk '{split($0,a,"-"); print a[1]}')
+#        export SHERPA_BUILD_NUMBER=$(echo $SHERPA_FULL_VERSION | awk '{split($0,a,"-"); print a[2]}')
+#        echo "Version: ${SHERPA_VERSION} Build Number: ${SHERPA_BUILD_NUMBER}"
+#        if [ -z ${SHERPA_VERSION} ] || [ -z ${SHERPA_BUILD_NUMBER} ] ; then
+#          echo "Error: SHERPA_VERSION or SHERPA_BUILD_NUMBER not set"
+#          exit 1
+#        fi
+#        source ${miniconda_loc}/etc/profile.d/conda.sh
+#        conda activate builder
+#        echo "conda build --python ${SHERPA_PYTHON_VERSION} --output-folder ${GITHUB_WORKSPACE}/packages recipes/conda"
+#        conda build --python ${SHERPA_PYTHON_VERSION} --output-folder ${GITHUB_WORKSPACE}/packages recipes/conda
+#
+#    - uses: actions/upload-artifact@v3
+#      with:
+#        path: ${{ github.workspace }}/packages/*/sherpa*bz2
+#        if-no-files-found: error
+#        retention-days: 3
 
   pre-deploy-test:
-    needs: [build-linux, build-macos]
+    needs: [build-linux]
     name: ${{ matrix.name }}
     runs-on: ${{ matrix.os }}
     strategy:
@@ -233,4 +233,4 @@ jobs:
         fi
         #We can switch this to use "--force" if we run into issues with the upload cutting or needing to re-run
         anaconda -t ${CONDA_UPLOAD_TOKEN} upload -u ${sherpa_channel} -l ${sherpa_label} packages/linux-64/sherpa*
-        anaconda -t ${CONDA_UPLOAD_TOKEN} upload -u ${sherpa_channel} -l ${sherpa_label} packages/osx-64/sherpa*
+#        anaconda -t ${CONDA_UPLOAD_TOKEN} upload -u ${sherpa_channel} -l ${sherpa_label} packages/osx-64/sherpa*
