Update the existing action to use setup-miniconda
As well as moving over to setup-miniconda, the macOS setup to
install XQuatz and the macOS SDK have been moved into a single
step.

Support for the docs-only build was removed as we are not
testing the docs build on the main CI anymore.

The conda configuration is now set up in

  etc/environment-linux|macos.yml

where the "type" is set by the new matrix.ostype setting.

Note that we try to use conda to install as much as possible
as there are strange failures if pip is used to install the
pytest machinery.

**NOTE** I made an attempt to update the build/test infrastructure
but this was spectacularly unsuccessful, so I have removed
this part of the PR.

Note that test=submodule install-type=install appears to re-build
the code when we get to runnig the test suite. This is not
ideal! I have been unable to improve on this (see preceeding
note).

diff --git a/.github/workflows/ci-conda-workflow.yml b/.github/workflows/ci-conda-workflow.yml
--- a/.github/workflows/ci-conda-workflow.yml
+++ b/.github/workflows/ci-conda-workflow.yml
@@ -17,6 +17,7 @@ jobs:
         include:
           - name: MacOS Full Build
             os: macos-latest
+            ostype: macos
             python-version: 3.8
             install-type: develop
             fits: astropy
@@ -24,15 +25,17 @@ jobs:
             matplotlib-version: 3
             xspec-version: 12.10.1s
 
-          - name: Linux Minimum Setup 
+          - name: Linux Minimum Setup
             os: ubuntu-latest
+            ostype: linux
             python-version: 3.8
             numpy-version: 1.17
-            install-type: develop 
+            install-type: develop
             test-data: none
 
           - name: Linux Full Build (Python 3.8)
-            os: ubuntu-latest 
+            os: ubuntu-latest
+            ostype: linux
             python-version: 3.8
             install-type: develop
             fits: astropy
@@ -42,16 +45,18 @@ jobs:
 
           - name: Linux Full Build (Python 3.7)
             os: ubuntu-latest
+            ostype: linux
             python-version: 3.7
             numpy-version: 1.15
             install-type: install
             fits: astropy
-            test-data: submodule 
+            test-data: submodule
             matplotlib-version: 3
             xspec-version: 12.10.1s
 
           - name: Linux Full Build (Python 3.6)
             os: ubuntu-latest
+            ostype: linux
             python-version: 3.6
             numpy-version: 1.11
             install-type: install
@@ -62,17 +67,23 @@ jobs:
 
           - name: Linux Build (w/o Astropy or Xspec)
             os: ubuntu-latest
-            python-version: 3.6 
+            ostype: linux
+            python-version: 3.6
             install-type: install
             test-data: package
             matplotlib-version: 2
 
           - name: Linux Build (w/o Matplotlib, Xspec, or test data)
             os: ubuntu-latest
+            ostype: linux
             python-version: 3.7
-            install-type: develop 
+            install-type: develop
             fits: astropy
             test-data: none
+
+    defaults:
+      run:
+        shell: bash -l {0}
 
     steps:
     - name: Checkout Code
@@ -80,7 +91,7 @@ jobs:
       with:
         submodules: 'True'
 
-    - name: Install XQuartz on macOS
+    - name: Install SDK/XQuartz on macOS
       if: runner.os == 'macOS'
       run: |
         curl -LO https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
@@ -94,8 +105,23 @@ jobs:
         hdiutil detach /Volumes/XQuartz-2.7.11
         rm XQuartz-2.7.11.dmg
 
-    - name: Conda Testing Setup (Xspec and DS9)
-      shell: bash
+        mkdir -p ${GITHUB_WORKSPACE}/10.9SDK
+        wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz -O MacOSX10.9.sdk.tar.xz
+        if [[ $? -ne 0 ]]; then
+          echo "macOS 10.9 SDK download failed"
+        fi
+        tar -C ${GITHUB_WORKSPACE}/10.9SDK -xf MacOSX10.9.sdk.tar.xz
+
+    - name: Setup Conda
+      uses: conda-incubator/setup-miniconda@v2
+      with:
+        activate-environment: build
+        auto-update-conda: true
+        python-version: ${{ matrix.python-version }}
+        use-only-tar-bz2: true
+        environment-file: etc/environment-${{ matrix.ostype }}.yml
+
+    - name: Install OTS
       env:
         PYTHONVER: ${{ matrix.python-version }}
         NUMPYVER: ${{ matrix.numpy-version }}
@@ -110,18 +136,14 @@ jobs:
 
     - name: Build Sherpa
       env:
-        PYTHON_LDFLAGS: " " 
+        PYTHON_LDFLAGS: " "
       run: |
-        source ${miniconda_loc}/etc/profile.d/conda.sh
-        conda activate build
         python setup.py ${{ matrix.install-type }}
 
     - name: Tests
       env:
         TEST: ${{ matrix.test-data }}
         XSPECVER: ${{ matrix.xspec-version }}
-        FITS: ${{ matrix.fits }} 
+        FITS: ${{ matrix.fits }}
       run: |
-        source ${miniconda_loc}/etc/profile.d/conda.sh
-        conda activate build
         source .github/scripts/test.sh
